PLAT-651 Rework UserActivityPage
softicar/platform pull request #125
Opened 2022-02-01 10:06 UTC by daniel-klose

2022-02-01 12:57 UTC, alexander-schmidt requested changes
I wonder if all of this is worth the hassle. Do we even need a separate page for this? How about simply adding two transient fields to `AGUserTable`:
1. last login date
2. number of days since last login

2022-02-01 12:57 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/user/login/overview/UserLoginOverviewDiv.java
> +	private void refresh() {
I think we should instead
- call `new UserLoginOverviewTableDivBuilder().build()` in the CTOR, and assign its return value (an `IEmfDataTableDiv`) to a field `dataTableDiv`
- change this `refresh` method to simply call ``dataTableDiv.refresh()`

This way, filters and other table settings won't get lost when somebody clicks the "Refresh" button.

2022-02-01 13:10 UTC, daniel-klose commented
Well, either we move all Login-Related Code to `AGUserTable` or dont move it at all.
Im completely against moving only parts of the Login-related code, either all nor nothing.

2022-02-02 07:46 UTC, alexander-schmidt requested changes

2022-02-02 08:15 UTC, alexander-schmidt approved these changes

2022-02-02 08:39 UTC, merged