PLAT-68 Add WorkflowTaskNotification for email notification
softicar/platform pull request #136
Opened 2022-02-08 14:31 UTC by daniel-klose

2022-02-10 08:17 UTC, alexander-schmidt requested changes

2022-02-10 08:17 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +	I18n0 CONFIGURE_SETTINGS = new I18n0("Configure settings")//
"Configure settings" seems overly complicated and unnecessarily long to me.
I think we should just go with "Settings" or "Preferences" - that's how such buttons or menu items are typically labelled, in pretty much any application out there.
We should also rename "AGWorkflowUserConfiguration" to "AGWorkflowUser[Settings|Preferences]", respectively.

2022-02-10 08:17 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/AGWorkflowUserConfiguration.sqml
> +	Boolean notify = TRUE
This might be too unspecific: Notify... _about what?_ or _upon what?_ or _how?_
I suggesto to rename this to `emailNotifications`

2022-02-10 16:18 UTC, alexander-schmidt requested changes

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +		.de("Arbeitsablauf-User-Konfiguration");
```suggestion
		.de("Arbeitsablauf-Benutzer-Konfiguration");
```

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +		.de("Arbeitsablauf-User-Konfiguration-Log");
```suggestion
		.de("Arbeitsablauf-Benutzer-Konfigurations-Log");
```

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +		.de("Arbeitsablauf-User-Konfiguration-Logs");
```suggestion
		.de("Arbeitsablauf-Benutzer-Konfigurations-Logs");
```

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +		.de("Arbeitsablauf-User-Konfigurationen");
```suggestion
		.de("Arbeitsablauf-Benutzer-Konfigurationen");
```

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/AGWorkflowUserConfigurationTable.java
> +	//FIXME for the future (everybody should change it's own but only admin may change it for everyone)
```suggestion
	// FIXME for the future (everybody should change their own configuration but only admins may change it for others)
```

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +	I18n0 EMAIL_NOTIFICATIONS_FOR_NEW_TASKS = new I18n0("Email notifications for new tasks")//
```suggestion
	I18n0 EMAIL_NOTIFICATIONS_FOR_NEW_TASKS = new I18n0("Email Notifications for New Tasks")//
```
I think we should use title-case here.

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/WorkflowUserConfigurationValidator.java
> +		if (tableRow.getSubstituteFrom() != null && tableRow.getSubstituteTo() != null) {
I think this condition should be integrated into `verifyValidFromBeforeValidTo`

2022-02-10 16:18 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/WorkflowUserConfigurationValidator.java
> +		if (tableRow.getSubstitute() == null) {
I think this condition should be integrated into `verifyEmptyValidFromAndValidTo`

2022-02-10 16:29 UTC, daniel-klose commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/WorkflowUserConfigurationValidator.java
> +			addError(AGWorkflowUserConfiguration.SUBSTITUTE_TO, WorkflowI18n.VALID_FROM_AFTER_VALID_TO);
need to change this `VALID_FROM_AFTER_VALID_TO` to something better and more fitting

2022-02-11 14:04 UTC, alexander-schmidt requested changes

2022-02-11 14:04 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +	I18n0 SUBSTITUTE_MUST_BE_DEFINED = new I18n0("Substitute must be defined")//
```suggestion
	I18n0 A_SUBSTITUTE_MUST_BE_DEFINED = new I18n0("A substitute must be defined.")//
```

2022-02-11 14:04 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +		.de("Eine Vertretung muss definiert sein");
```suggestion
		.de("Eine Vertretung muss definiert sein.");
```

2022-02-11 14:04 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +	I18n0 SUBSTITUTE_SET = new I18n0("Substitute set")//
```suggestion
	I18n0 SUBSTITUTE_SET = new I18n0("Substitute defined")//
```
The label directly above states: "A substitute must be _defined_." We should settle for either "set" or "define".

2022-02-11 14:04 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/WorkflowI18n.java
> +		.de("Vertretung gesetzt");
```suggestion
		.de("Vertretung definiert");
```

2022-02-11 14:04 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/AGWorkflowUserConfiguration.sqml
> +}
...missing newline vs. my OCD

2022-02-11 14:04 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/user/configuration/AGWorkflowUserConfigurationLog.sqml
> +}
huh, again

2022-02-11 14:24 UTC, alexander-schmidt approved these changes

2022-02-11 14:26 UTC, alexander-schmidt approved these changes

2022-02-11 14:31 UTC, merged