PLAT-395 Standard Configuration of Programs
softicar/platform pull request #160
Opened 2022-02-28 13:00 UTC by thees-k

- Add method getDefaultCronExpression() to IProgram
- ProgramStandardConfiguration registers default schedule of programs, too
- Implement getDefaultCronExpression() for all programs of platform
- Delete WorkflowProgramStandardConfiguration because not necessary anymore

2022-02-28 13:06 UTC, thees-k commented
![PLAT-395](https://user-images.githubusercontent.com/74466399/155988366-d27cd71c-c4e3-4995-a82f-0f7e0b929a3f.png)

2022-02-28 13:07 UTC, oliver-richers requested changes

2022-02-28 13:07 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/standard/configuration/ProgramStandardConfiguration.java
> +		Optional<IEmfSourceCodeReferencePoint> point = EmfSourceCodeReferencePoints.getReferencePoint(uuid.getUuid());
better use `getReferencePointOrThrow(IProgram.class, uud)`

2022-02-28 13:07 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/program/IProgram.java
> +	default String getDefaultCronExpression() {
should provide a Javadoc comment, especially concerning the possible results, e.g. `""`, `null`, etc.

2022-03-01 09:31 UTC, oliver-richers requested changes

2022-03-01 09:31 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/program/IProgram.java
> +	 * @return An Optional with a cron expression, or an empty Optional.
```suggestion
	 * @return an optional cron expression
```

2022-03-01 12:43 UTC, oliver-richers approved these changes

2022-03-01 12:44 UTC, merged