PLAT-808-3 Create Basic Maintenance Page & Logic
softicar/platform pull request #252
Opened 2022-05-11 14:15 UTC by daniel-klose

- This PR only aims to build a basic management page & basic action for managing maintenances
  - This does not include all the session invalidation, user info and login prevention logic
  - The above mentioned will be done in the next PR

2022-05-11 16:05 UTC, oliver-richers requested changes

2022-05-11 16:05 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/action/StartMaintenanceAction.java
> +			.and(MaintenancePredicates.NO_MAINTENANCE_ACTIVE);
- IMO `NEXT_IN_LINE` und `NO_MAINTENANCE_ACTIVE` should not be added here
- instead, NEXT_IN_LINE should trigger a confirmation in `handleClick`, that they are about to start a maintenance window which is not next in line
- NO_MAINTENANCE_ACTIVE should trigger an exception in `handleClick`

2022-05-11 16:05 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/status/AGMaintenanceStatus.java
> +public class AGMaintenanceStatus extends AGMaintenanceStatusGenerated implements IEntity {
as already suggested: I think the name `AGMaintenanceWindowState` would be preferable

2022-05-12 07:24 UTC, daniel-klose commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenanceTable.java
> +		authorizer.setCreationRole(CoreRoles.MAINTENANCE_ADMINISTRATOR);
hm oh right, seems i forgot to change my notes

2022-05-12 07:25 UTC, daniel-klose commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenanceTable.java
> +		configuration.setEditPredicate(MaintenancePredicates.PENDING);
well if you say so

2022-05-12 07:27 UTC, daniel-klose commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/MaintenancePredicates.java
> +	IEmfPredicate<AGMaintenance> NO_MAINTENANCE_ACTIVE = MAINTENANCE_ACTIVE.not();
well yeah, predicates are scoped to the object, or is there a way to make a predicate without one?

2022-05-12 07:42 UTC, daniel-klose commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenance.sqml
> +	DayTime expectedStart
IMO this is the way to announce maintenances (as ive seen in games etc)
they always say that the maintenance starts at XX and they expect it to end in XX hours or at XX:XX
Also, as we talked, maintenances can be started early, finished early or later, so expected kinda signifies "around that time" for the users

2022-05-12 07:43 UTC, daniel-klose commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenance.java
> +			.orElse(isPending());
woops, forgot to change this one

2022-05-12 09:13 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenance.sqml
> +	DayTime expectedStart
ok

2022-05-12 09:22 UTC, oliver-richers approved these changes
acceptable, but added suggestions

2022-05-12 09:22 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/CoreI18n.java
> +	I18n0 A_MAINTENANCE_IS_ALREADY_IN_PROGRESS = new I18n0("A maintenance is already in progress.")//
should be `maintenance window`

2022-05-12 09:22 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/AGMaintenanceWindow.java
> +	public static boolean isMaintenanceInProgress() {
from the name, it is not very obvious that this is a static method, a caller might easily confuse it with the method isInProgress()... suggested name: existsMaintenanceWindowInProgress

2022-05-12 09:22 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/action/CancelMaintenanceAction.java
> +public class CancelMaintenanceAction implements IEmfManagementAction<AGMaintenanceWindow> {
CancelMaintenanceAction -> CancelMaintenanceWindowAction

2022-05-12 09:22 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/action/FinishMaintenanceAction.java
> +public class FinishMaintenanceAction implements IEmfManagementAction<AGMaintenanceWindow> {
FinishMaintenanceAction -> FinishMaintenanceWindowAction

2022-05-12 09:22 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/action/StartMaintenanceAction.java
> +public class StartMaintenanceAction implements IEmfManagementAction<AGMaintenanceWindow> {
StartMaintenanceAction -> StartMaintenanceWindowAction

2022-05-12 09:22 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/maintenance/state/AGMaintenanceState.java
> +public class AGMaintenanceState extends AGMaintenanceStateGenerated implements IEntity {
AGMaintenanceState -> AGMaintenanceWindowState

2022-05-12 10:50 UTC, oliver-richers approved these changes

2022-05-12 11:11 UTC, merged