PLAT-882 Turn IDomDisableable into IDomInput
softicar/platform pull request #291
Opened 2022-05-25 13:29 UTC by vdcstr

- `IDomInput` (ex. `IDomDisableable`):
  - No longer provides default implementations.
  - Let `IDomValueInput` extend `IDomInput`.
  - Added final wrapper implementations for `setEnabled` / `isEnabled` in various places.
- Added framework-internal utility class `DomNodes`.
- `StoredFileUploadDiv`:
  - Created unit tests.
  - Removed orphaned features.
  - Fixed unsafe disabling.
  - Fixed file downloads being impossible when disabled.
  - Fixed wrong package.
- Replaced `IStoredFileUploadSaveHook` with functional interface `IStoredFileUploadFileChangeHandler`.
- Removed most of the overwhelmingly-complex, orphaned code related to `IDbRecord` collections.
  - Only retained what's necessary for `AGStoredFileSet` and `EmfTestObjectSet`.

2022-05-27 08:09 UTC, oliver-richers requested changes

2022-05-30 07:18 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/attribute/StoredFileInput.java
> +		this.file = addedFiles.stream().findFirst().orElse(null);
that `TODO` will be added

2022-05-30 07:20 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/set/attribute/StoredFileSetInput.java
> +		updateFileSet(files);
that `TODO` will be added to the method declaration of functional interface `IStoredFileUploadFileChangeHandler`

2022-05-30 07:21 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/set/attribute/StoredFileSetInput.java
> +		updateFileSet(files);
see above

2022-05-30 07:27 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/upload/StoredFileUploadTable.java
> +		}
Well, those are not _quite_ the same: There's a "is-realized-via" relation between "readonly" and "disabled". Also, generally, "readonly" has stronger contextual semantics.
That being said: If (!) there is no reasonable scenario in which we would use "disabled" while "readonly" would not make sense, we could indeed rename everything to "readonly". Assuming that we'll come up with an elegant name for that interface ^^

2022-05-30 07:31 UTC, alexander-schmidt commented on platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/node/tester/AbstractDomNodeTester.java
> +			.map(button -> button.isDisabled())
indeed

2022-05-30 07:34 UTC, alexander-schmidt commented on platform-dom/src/main/java/com/softicar/platform/dom/elements/testing/node/tester/AbstractDomNodeTester.java
> +			.ofNullable(node)
Hm. Seems like it cannot, according to `IDomNodeTesterFindMethods.getNode` and the `final` modifier on `AbstractDomNodeTester.node`.

2022-05-30 07:36 UTC, alexander-schmidt commented on platform-dom/src/main/java/com/softicar/platform/dom/elements/time/DomTimeInput.java
> +		return hourInput.isDisabled() && minuteInput.isDisabled() && secondInput.isDisabled();
hm. yea.

2022-05-30 07:38 UTC, alexander-schmidt commented on platform-dom/src/main/java/com/softicar/platform/dom/elements/time/day/DomDayInput.java
> +		return dayInput.isDisabled() && dayButton.isDisabled();
hm. yea.

2022-05-30 10:17 UTC, oliver-richers approved these changes
nice

2022-05-30 10:20 UTC, merged