PLAT-521 Adapt WorkflowTaskManager:closeAllPreviousTasks
softicar/platform pull request #32
Opened 2021-11-11 15:02 UTC by daniel-klose

2021-11-11 16:09 UTC, alexander-schmidt requested changes

2021-11-11 16:09 UTC, alexander-schmidt commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/task/WorkflowTaskManager.java
> +	public void closeAllOpenTasks() {
since this method can now be called externally, it needs a transaction

2021-11-11 20:16 UTC, oliver-richers requested changes

2021-11-12 09:00 UTC, oliver-richers approved these changes

2021-11-12 09:12 UTC, merged