PLAT-100 Fix setPlaceholder for some IEmfInputs
softicar/platform pull request #53
Opened 2021-11-29 15:19 UTC by daniel-klose

2021-11-29 15:21 UTC, daniel-klose commented
The Problem described in PLAT-100 references the class `BigDecimalInputWithOptionalPlaceholder`

2021-11-29 15:53 UTC, alexander-schmidt requested changes
I think we need to change our CSS now, and ditch the right-alignment of numerical inputs.

Rationale: Imagine a `DomLabelGrid` with a couple of stacked inputs, and some of those having lift-aligned placeholders while the rest would have right-aligned placeholders. This would look incredibly poor.

2021-11-30 07:51 UTC, daniel-klose commented
![image](https://user-images.githubusercontent.com/90852097/144007028-d9cd5259-7af1-41a5-9547-18560a5e044c.png)
Now looks like this

2021-11-30 07:58 UTC, alexander-schmidt approved these changes

2021-11-30 08:12 UTC, alexander-schmidt approved these changes

2021-11-30 08:14 UTC, merged