PLAT-1331-3 Enable StoredFileFileSystemContentStore
softicar/platform pull request #744
Opened 2023-03-22 12:15 UTC by alexander-schmidt

- Stored Files can now be saved to either SMB shares or local file system directories.
  - An appropriate `IStoredFileContentStore` implementation is chosen according to the protocol part of the repository URL, as defined in `Core`.`StoredFileRepository`.
  - e.g. `StoredFileSmbContentStore` will be used for URLs like `smb://host/share`
  - e.g. `StoredFileFileSystemContentStore` will be used for URLs like `file:///dir/subdir`
- Established `StoredFileContentStores` as a central place to retrieve (SMB-based or file-system-based) `IStoredFileContentStore` instances.
  - This puts an end to seemingly-random calls to file store implementation constructors throughout the code base.
- `IStoredFileContentStore`: merged `isEnabled`, `isReady` and `isAvailable` to just one method, `isAvailable`.
  - All existing implementations of `isEnabled` were either trivial or nonsensically-arbitrary.
- `StoredFileContentInputStreamCreator` now checks whether a file store is available before trying to access it.

2023-03-22 12:18 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/store/StoredFileContentStoreFactory.java
> +	private static class SimpleUrl {
`java.net.URL` throws for URLs that start with `smb`, so I built this.

2023-03-22 12:19 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/store/StoredFileContentStoreFactory.java
> +			this.path = Trim.trimPrefix(matcher.group(2), "//");
Note that the following URLs are all valid, in principle:
```
file:/dir/subdir    - an absolute path (short form)
file://dir/subdir   - a relative path
file:///dir/subdir  - an absolute path
```

2023-03-22 12:19 UTC, alexander-schmidt commented on platform-dom/src/main/resources/com/softicar/platform/dom/dom-wiki-elements-style.css
> +	box-shadow: 0 0 0 1px #cccccc inset;
Fixed random typo / broken declaration

2023-03-22 12:20 UTC, alexander-schmidt commented on platform-dom/src/main/resources/com/softicar/platform/dom/dom-wiki-elements-style.css
> +	margin-top: 0;
Before:
![image](https://user-images.githubusercontent.com/15086658/224008846-ca4f5a4b-348b-4840-a39a-8f86dd31820a.png)

After:
![image](https://user-images.githubusercontent.com/15086658/224008864-8c66c689-ce4b-4413-bda6-11989afaaf6b.png)

2023-03-22 12:22 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/StoredFileContentUploader.java
> +		if (store.get().isAvailable()) {
Abundant use of `store.get()` here and below should probably be fixed / beautified.

2023-03-29 09:22 UTC, oliver-richers requested changes

2023-03-29 09:34 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/cleanup/StoredFilesCleanupProgram.java
> +		primaryContentStore.ifPresent(store -> new FileStoreTmpFolderCleaner(store).cleanAll());
ok

2023-03-29 11:20 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/StoredFileContentOutputStreamCreator.java
> +		this.store = StoredFileContentStores.getPreferredAvailableContentStore();
We could, for sure, remove the fallback to secondary file stores here. However, the fallback to database-based file storage (which is not available as an `IStoredFileContentStore`) would have to remain in `StoredFileContentUploader`.
Ack?

2023-03-29 11:28 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/StoredFileContentUploader.java
> +	public StoredFileContentUploader(IStoredFileDatabase database, AGStoredFile storedFile, Optional<IStoredFileContentStore> store) {
Added non-null requirements and removed `Optional`-based CTOR.

2023-03-29 11:31 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/StoredFileContentUploader.java
> +		store.get().createDirectories(folderName);
Granted - yet, the Java API pretty much consistently uses `directory`. So consistently using the latter in our code as well should eliminate unnecessary synonyms.

2023-03-29 11:35 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/store/IStoredFileContentStore.java
> +	boolean isAvailable();
Opted for `isAccessible`.

2023-03-29 11:39 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/store/StoredFileContentStoreFactory.java
> +			this.path = Trim.trimPrefix(matcher.group(2), "//");
Added a Javadoc block above `SimpleUrl`.

2023-03-29 11:41 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/store/StoredFileContentStores.java
> +	public static Collection<IStoredFileContentStore> getAvailableContentStores() {
Indeed, `accessible` is better.

2023-03-29 11:41 UTC, alexander-schmidt commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/store/StoredFileContentStores.java
> +	public static Optional<IStoredFileContentStore> getPreferredAvailableContentStore() {
we don't. it was removed.

2023-03-29 12:31 UTC, oliver-richers commented on platform-core-module/src/test/java/com/softicar/platform/core/module/file/stored/content/StoredFileContentUploaderTest.java
> -	public void usesDatabaseOutputStreamIfFileStoreDisabled() {
ok

2023-03-29 12:36 UTC, oliver-richers commented on platform-core-module/src/main/java/com/softicar/platform/core/module/file/stored/content/StoredFileContentOutputStreamCreator.java
> +		this.store = StoredFileContentStores.getPreferredAvailableContentStore();
that is fine, IMO

2023-03-29 12:47 UTC, merged