EXP-2801 Fix deferred initializers not being processed upon initial document creation
softicar/platform pull request #764
Opened 2023-04-11 16:09 UTC by alexander-schmidt

2023-04-11 16:16 UTC, alexander-schmidt commented on platform-ajax/src/main/java/com/softicar/platform/ajax/document/creation/AjaxDocumentCreationService.java
> +		document.getDeferredInitializationController().handleAllAppended();
Note that we still have a second call to `IDomDeferredInitializationController#handleAllAppended` which is in `DomEventHandlerNodeCaller#call`. That one is used whenever `AjaxDomEventService` handles an event.

I theory, those two calls could be unified to a single one in `AbstractAjaxDocumentService` but that would entail quite some refactoring which is not worth the effort.

2023-04-12 07:00 UTC, oliver-richers requested changes
Can you test this, and append some videos?

2023-04-12 07:40 UTC, alexander-schmidt commented
Something went wrong with saving the attached GIFs. Should be visible now.

2023-04-12 07:54 UTC, daniel-klose approved these changes

2023-04-12 07:55 UTC, merged