EXP-2953 WorkflowAutoTransitionsExecutor: Don't Throw MultiException if Only 1 Exception Occurred
softicar/platform pull request #830
Opened 2023-06-02 13:08 UTC by thees-k

If only one `SofticarUserException` occurred, throw it as it is to forward its message to the user.

2023-06-05 10:59 UTC, oliver-richers requested changes

2023-06-05 10:59 UTC, oliver-richers commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionsExecutor.java
> +			var causeThrowable = exceptions.iterator().next().getCause();
Das ist ziemlich gehackt. Wir nehmen explizit an, dass es sich genau um ein Wrapping handelt. Aber eine gute Loesung ist gar nicht so einfach.

Eigentlich brauchen wir den ganzen Kram mit dem `ExceptionsCollector` und `WorkflowAutoTransitionFailedException` doch nur, wenn wir im Job-Modus sind. Im interaktiven User-Modus geht es eh nur um ein Item, daher brauchen wir `WorkflowAutoTransitionFailedException` nicht und auch nicht `ExceptionsCollector`.

Vorschlag: Wir aendern einfach `WorkflowAutoTransitionsExecutor` von so:
```java
			} catch (Throwable throwable) {
				Log.fverbose("FAILURE -- see exceptions below");
				exceptionsCollector.add(new WorkflowAutoTransitionFailedException(throwable, item));
				result.addFailed(item);
			}
```
nach so ab:
```java
			} catch (Throwable throwable) {
				if (CurrentUser.get().isSystemUser()) {
					Log.fverbose("FAILURE -- see exceptions below");
					exceptionsCollector.add(new WorkflowAutoTransitionFailedException(throwable, item));
					result.addFailed(item);
				} else {
					throw throwable;
				}
			}
```

2023-06-07 07:56 UTC, thees-k commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionsExecutor.java
> +			var causeThrowable = exceptions.iterator().next().getCause();
Habe das jetzt so angepasst, wie von dir vorgeschlagen.

Aber funktioniert das nicht erst zuverlässig, wenn PLAT-1386 umgesetzt ist?

2023-06-08 09:08 UTC, oliver-richers requested changes

2023-06-08 09:08 UTC, oliver-richers commented on platform-workflow-module/src/main/java/com/softicar/platform/workflow/module/workflow/transition/execution/auto/WorkflowAutoTransitionsExecutor.java
> +	}
```suggestion
	 * @param collectExceptions
	 *                 <i>true</i> to collect all exceptions and throw a {@link MultiException}
	 *                 at the end; <i>false</i> to immediately throw any occurring exception
	 * @return this
	 */
	public WorkflowAutoTransitionsExecutor setCollectExceptions(boolean collectExceptions) {

		this.collectExceptions = collectExceptions;
		return this;
	}
```

2023-06-08 09:24 UTC, oliver-richers approved these changes

2023-06-08 09:31 UTC, merged